### ISSUE TITLE
server crash on gamestage add

### ISSUE THREAD

**Issue by superon** [Dolphin2Point1/GameStagesFabric#1]
https://pastebin.com/ftLmpEe4
when attempting to issue a gamestage to a player as mention in the comments, thinking i should've posted here instead, only not sure if it's an issue or just me being stuper

**Comment by TigerWalts** [comment]
The `Text.of("message")` method is only available clientside.

- https://github.com/Dolphin2Point1/GameStagesFabric/blob/master/src/main/java/com/dolphin2point0/game_stages_fabric/command/GameStagesBasicCommands.java

Replacing it with `new LiteralText("message")` (`net.minecraft.text.LiteralText`) will fix the issue.
